-- MySQL Script generated by MySQL Workbench
-- Sun Feb 24 22:40:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mappa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mappa` (
  `idMappa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMappa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stazione` (
  `idStazione` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `idMappa` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  PRIMARY KEY (`idStazione`, `idMappa`),
  INDEX `fk_Stazione_Mappa_idx` (`idMappa` ASC) VISIBLE,
  CONSTRAINT `fk_Stazione_Mappa`
    FOREIGN KEY (`idMappa`)
    REFERENCES `mydb`.`Mappa` (`idMappa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Linea` (
  `idLinea` INT NOT NULL AUTO_INCREMENT,
  `Colore` VARCHAR(45) NULL,
  `idMappa` INT NOT NULL,
  PRIMARY KEY (`idLinea`, `idMappa`),
  INDEX `fk_Linea_Mappa1_idx` (`idMappa` ASC) VISIBLE,
  CONSTRAINT `fk_Linea_Mappa1`
    FOREIGN KEY (`idMappa`)
    REFERENCES `mydb`.`Mappa` (`idMappa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Collegamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Collegamento` (
  `idCollegamento` INT NOT NULL AUTO_INCREMENT,
  `distanza` INT NOT NULL,
  `idStazionePartenza` INT NOT NULL,
  `idStazioneArrivo` INT NOT NULL,
  `idLinea` INT NOT NULL,
  PRIMARY KEY (`idCollegamento`, `idStazionePartenza`, `idStazioneArrivo`, `idLinea`),
  INDEX `fk_Collegamento_Stazione1_idx` (`idStazionePartenza` ASC) VISIBLE,
  INDEX `fk_Collegamento_Stazione2_idx` (`idStazioneArrivo` ASC) VISIBLE,
  INDEX `fk_Collegamento_Linea1_idx` (`idLinea` ASC) VISIBLE,
  CONSTRAINT `fk_Collegamento_Stazione1`
    FOREIGN KEY (`idStazionePartenza`)
    REFERENCES `mydb`.`Stazione` (`idStazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collegamento_Stazione2`
    FOREIGN KEY (`idStazioneArrivo`)
    REFERENCES `mydb`.`Stazione` (`idStazione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collegamento_Linea1`
    FOREIGN KEY (`idLinea`)
    REFERENCES `mydb`.`Linea` (`idLinea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
